Repository dotnet/project-system, pull requests merged in 2018-07, with the labels that each got.

#3698 Merge MSRC 43523 into public dev15.8.x
  src/Microsoft.VisualStudio.Editors/Common/Utils.vb
  src/Microsoft.VisualStudio.Editors/PropPages/CompilePropPage2.vb
  src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceEditorDesignerLoader.vb
  src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceFile.vb
  src/Microsoft.VisualStudio.Editors/Resources/Designer.Designer.vb
  src/Microsoft.VisualStudio.Editors/Resources/Designer.resx
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.cs.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.de.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.es.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.fr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.it.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.ja.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.ko.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.pl.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.ru.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.tr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Designer.zh-Hant.xlf
Labels: Proactive merge allowed

#3706 Version padding for 15.8
  build/Versions.props
Labels: Proactive merge allowed

#3707 Hide the "Auto-generated Binding Redirects" check box
  src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPage.vb
  src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageInternalBase.vb
  src/Microsoft.VisualStudio.Editors/PropPages/ApplicationPropPageVBWinForms.vb
  src/Microsoft.VisualStudio.Editors/PropPages/WPF/ApplicationPropPageVBWPF.vb
Labels: Pending director approval

#3786 Resx string editor quality-of-life improvements
  src/Microsoft.VisualStudio.Editors/DesignerFramework/DesignerDataGridView.vb
  src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceStringTable.vb
Labels: Community

#3797 Add support for metafiles to the Resx editor
  src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceTypeEditorBitmap.vb
  src/Microsoft.VisualStudio.Editors/ResourceEditor/ResourceTypeEditorImageBase.vb
  src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.Designer.vb
  src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.resx
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.cs.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.de.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.es.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.fr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.it.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ja.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ko.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pl.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ru.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.tr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hant.xlf
Labels: Community

#3768 Added support for launching a class library project using the run project command
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/Debug/ConsoleDebugLaunchProviderTests.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/ConsoleDebugTargetsProvider.cs
Labels: Community

#3782 fixing tab ordering in debug options page
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
Labels: Approved to merge

#3808 Sdk telemetry
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/ITelemetryServiceFactory.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Telemetry/SDKVersionTelemetryTests.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.SDKVersionTelemetryServiceInstance.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/SDKVersionTelemetryServiceComponent.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.cs.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.de.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.es.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.fr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.it.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ja.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ko.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.pl.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.pt-BR.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.ru.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.tr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.zh-Hans.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/xlf/ConfigurationGeneral.xaml.zh-Hant.xlf
Labels: Approved to merge
