Repository dotnet/project-system, pull requests merged in 2019-02, with the labels that each got.

#4520 Fix changed project references not causing rebuild
  setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/CommonFiles.swr
Labels: Approved to merge

#4223 Adding License Expression and License File to Package Property Page
  src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.Designer.vb
  src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.resx
  src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.vb
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.cs.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.de.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.es.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.fr.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.it.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ja.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ko.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pl.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ru.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.tr.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hant.xlf
  src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.Designer.vb
  src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.resx
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.cs.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.de.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.es.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.fr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.it.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ja.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ko.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pl.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ru.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.tr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hant.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml
Labels: Triaged

#4563 Fix hang in GetWorkspaceContextIdFromActiveContext
  src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IActiveEditorContextTrackerFactory.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/LanguageServices/WorkspaceProjectContextHostInstanceTests.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/LanguageServices/ActiveEditorContextTrackerTests.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ActiveEditorContextTracker.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/IActiveEditorContextTracker.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/WorkspaceProjectContextHost.WorkspaceProjectContextHostInstance.cs
Labels: Triaged

#4586 Unresolved child test excludes non-visible children
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
Labels: Feature-Dependency-Node
