Repository dotnet/project-system, pull requests merged in 2020-01, with the labels that each got.

#5764 Consider existing child captions when preventing duplicates
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Labels: Feature-Import-Tree

#5775 Import tree display order
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Labels: Feature-Import-Tree

#5802 Add help text to text boxes in Debug
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/DebugPageControl.xaml
Labels: Tenet-User Friendly

#5814 Setup up notifications for new PRs
  .github/workflows/issues-to-teams.yml
  .github/workflows/prs-to-teams.yml
Labels: Area-Infrastructure

#5807 Add 'Nullable' option to the build property page
  src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.Designer.vb
  src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx
  src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.cs.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.de.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.es.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.fr.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.it.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ja.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ko.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pl.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.ru.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.tr.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/BuildPropPage.zh-Hant.xlf
  src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.Designer.vb
  src/Microsoft.VisualStudio.Editors/Resources/Microsoft.VisualStudio.Editors.Designer.resx
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.cs.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.de.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.es.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.fr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.it.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ja.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ko.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pl.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.ru.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.tr.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/Resources/xlf/Microsoft.VisualStudio.Editors.Designer.zh-Hant.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralConfiguredBrowseObject.xaml
Labels: Feature-AppDesigner

#5828 Hide "Nullable" setting from legacy build prop page
  src/Microsoft.VisualStudio.AppDesigner/PropPages/HiddenIfMissingPropertyControlData.vb
  src/Microsoft.VisualStudio.AppDesigner/PublicAPI.Unshipped.txt
  src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.vb
Labels: Feature-AppDesigner

#5830 Don't require analyzers to be in evaluation data
  src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/AnalyzerRuleHandler.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/Tree/Dependencies/Subscriptions/RuleHandlers/DependenciesRuleHandlerBase.cs
Labels: Feature-Dependency-Node
