Repository dotnet/project-system, pull requests merged in 2020-07, with the labels that each got.

#6323 Restore case insensitive dependency ID comparison
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyId.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependencyModelExtensions.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/AddDependencyContext.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/DeduplicateCaptionsSnapshotFilter.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/RemoveDependencyContext.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/UnresolvedDependenciesSnapshotFilter.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DeduplicateCaptionsSnapshotFilterTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotFilterTestsBase.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/ImplicitDependenciesSnapshotFilterTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/UnresolvedDependenciesSnapshotFilterTests.cs
Labels: Feature-Dependency-Node

#6330 Track dependency diagnostic level at snapshot level
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactory.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyModel.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependenciesViewModelFactory.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependencyModelExtensions.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs
Labels: Feature-Dependency-Node

#6332 Add comments to ProjectTypeCapabilities
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/Packaging/ProjectTypeCapabilities.cs
Labels: auto-merge

#6336 Increase Version
  build/import/Versions.props
Labels: auto-merge

#6337 Update Readme to include 16.8 and remove 16.5
  README.md
Labels: auto-merge

#6338 Fix lingering warning icon on SDK references
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs
Labels: Feature-Dependency-Node

#6339 Avoid starting restore dataflow on inactive configurations
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PackageRestore/PackageRestoreProgressTracker.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/IImplicitlyActiveService.cs
Labels: auto-merge

#6341 Add unit test for differences in dependency ID/provider type capitalisation
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
Labels: Area-Testing, Feature-Dependency-Node

#6333 [16.7] Track dependency diagnostic level at snapshot level
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactory.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/DependencyModel.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependenciesViewModelFactory.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/IDependencyModelExtensions.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Dependency.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/SdkAndPackagesDependenciesSnapshotFilter.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependency.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/IDependencyExtensions.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/SdkAndPackagesDependenciesSnapshotFilterTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependency.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TestDependencyExtensions.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Mocks/DependenciesSnapshotFactory.cs
Labels: Feature-Dependency-Node

#6184 Turn on CPS diagnostics for debugging
  Launch.cmd
  setup/ProjectSystemSetup/Properties/launchSettings.json
Labels: auto-merge

#6352 Move URI to secret and remove if statement
  .github/workflows/teams-notifications.yml
Labels: Area-Infrastructure

#6375 Pull ProjectDebugger.xaml from neutral resoure
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Labels: auto-merge

#6381 Workaround SourceRoot without urls
  build/import/Workarounds.targets
Labels: auto-merge

#6380 Do not auto-initialize VisualBasicNamespaceImportsList
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Automation/VisualBasic/VisualBasicNamespaceImportsList.cs
Labels: auto-merge

#6372 Posting to Teams workflow should also update PRs
  .github/workflows/teams-notifications.yml
Labels: auto-merge

#6365 [16.7] Protect against exception due to empty string
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceAssemblyAttachedCollectionSourceProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/Implementation/FrameworkReferenceIdentity.cs
Labels: Feature-Dependency-Node

#6366 [16.7] Fix integer overflow exception
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/DependenciesTreeSearchContext.cs
Labels: Feature-Dependency-Node

#6387 Remove more unused suppressions
  src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerLoader.vb
  src/Microsoft.VisualStudio.AppDesigner/DesignerFramework/DesignerMenuCommand.vb
  src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerLoader.vb
  src/Microsoft.VisualStudio.AppDesigner/PropPageDesigner/PropPageDesignerView.vb
  src/Microsoft.VisualStudio.AppDesigner/PropPages/SKUMatrix.vb
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ApplicationPropertyPage.xaml.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ExecutableDebugPropertyPage.xaml.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ParentDebugPropertyPage.xaml.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/ProjectDebugPropertyPage.xaml.cs
Labels: auto-merge

#6388 Unify analyzer packages
  build/import/HostAgnostic.props
  build/import/Packages.targets
Labels: auto-merge

#6389 Avoid awaiting a null value
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Labels: auto-merge

#6385 Fix priority ordering of attached tree children
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/AttachedCollections/AggregateRelationCollectionSource.cs
Labels: Feature-Dependency-Node

#6404 Suppress noise in generated code
  src/Microsoft.VisualStudio.AppDesigner/GlobalSuppressions.vb
  src/Microsoft.VisualStudio.Editors/GlobalSuppressions.vb
  src/Microsoft.VisualStudio.Editors/PropPages/AdvancedServicesDialog.vb
  src/Microsoft.VisualStudio.Editors/PropPages/ServicesAuthenticationForm.vb
  src/Microsoft.VisualStudio.Editors/PropPages/ServicesPropPage.vb
  src/Microsoft.VisualStudio.Editors/PropPages/ServicesPropPageConfigHelper.vb
  src/Microsoft.VisualStudio.Editors/XmlToSchema/InputXmlForm.vb
  src/Microsoft.VisualStudio.Editors/XmlToSchema/PasteXmlDialog.vb
  src/Microsoft.VisualStudio.Editors/XmlToSchema/Utilities.vb
  src/Microsoft.VisualStudio.Editors/XmlToSchema/WebUrlDialog.vb
  src/Microsoft.VisualStudio.Editors/XmlToSchema/Wizard.vb
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/GlobalSuppressions.cs
Labels: auto-merge

#6405 Promote all APIs as shipped
  src/Microsoft.VisualStudio.AppDesigner/PublicAPI.Shipped.txt
  src/Microsoft.VisualStudio.AppDesigner/PublicAPI.Unshipped.txt
  src/Microsoft.VisualStudio.Editors/PublicAPI.Shipped.txt
  src/Microsoft.VisualStudio.Editors/PublicAPI.Unshipped.txt
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Unshipped.txt
  src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Shipped.txt
  src/Microsoft.VisualStudio.ProjectSystem.Managed/PublicAPI.Unshipped.txt
Labels: auto-merge

#6406 Upgrade compiler to latest version
  build/import/Packages.targets
Labels: auto-merge

#6394 Register project properties editor with placeholder UI
  src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerEditorFactory.vb
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client.csproj
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Packaging/ManagedProjectSystemClientPackage.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/ProjectProperties/ProjectPropertiesEditorFactory.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/Utilities/WaitCursor.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/VSPackage.resx
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.cs.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.de.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.es.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.fr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.it.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.ja.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.ko.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.pl.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.pt-BR.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.ru.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.tr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.zh-Hans.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.Client/xlf/VSPackage.zh-Hant.xlf
Labels: Feature-AppDesigner

#6410 Remove unneeded suppressions
  src/Microsoft.VisualStudio.AppDesigner/GlobalSuppressions.vb
  src/Microsoft.VisualStudio.Editors/GlobalSuppressions.vb
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/GlobalSuppressions.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/GlobalSuppressions.cs
Labels: auto-merge

#6407 Add a Package property page
  setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/CommonFiles.swr
  src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/InterceptedProjectProperties/PackagePropertyPage/NeutralLanguageValueProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Properties/NeutralLanguageEnumProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.cs.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.de.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.es.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.fr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.it.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ja.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ko.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pl.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.pt-BR.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.ru.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.tr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hans.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/xlf/PackagePropertyPage.xaml.zh-Hant.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.Designer.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/Resources.resx
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.cs.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.de.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.es.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.fr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.it.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ja.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ko.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pl.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.pt-BR.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.ru.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.tr.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hans.xlf
  src/Microsoft.VisualStudio.ProjectSystem.Managed/xlf/Resources.zh-Hant.xlf
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/InterceptedProjectProperties/NeutralLanguageValueProviderTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Properties/NeutralLanguageEnumProviderTests.cs
Labels: Feature-Codespaces

#6421 Simplify publishing values
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsChangeTracker.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TempPE/DesignTimeInputsFileWatcher.cs
Labels: auto-merge

#6422 Downgrade analyzers during dev builds to warnings
  .editorconfig
Labels: auto-merge

#6423 Minor analysis cleanup
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/PackagePropertyPage.xaml.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Debug/LaunchProfileTests.cs
Labels: auto-merge

#6436 Remove reference to non-existent rule
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Labels: auto-merge

#6424 Fix root graft tree provider GetPath logic
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs
Labels: Feature-Dependency-Node, Feature-Import-Tree

#6437 Remove DotNetCliToolReference from BrowseObject context
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Labels: auto-merge
