Repository dotnet/project-system, pull requests merged in 2021-01, with the labels that each got.

#6814 Fix package reference removal
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
Labels: Feature-Dependency-Node

#6815 Fix a11y issue: Name must not include LocalizedControlType.
  src/Microsoft.VisualStudio.Editors/PropPages/PackagePropPage.resx
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.cs.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.de.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.es.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.fr.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.it.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ja.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ko.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pl.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.ru.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.tr.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/PropPages/xlf/PackagePropPage.zh-Hant.xlf
Labels: Tenet-User Friendly

#6810 Remove filtering of dependency removals
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/DependenciesSnapshotFilterBase.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/IDependenciesSnapshotFilter.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/Filters/RemoveDependencyContext.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshotTests.cs
Labels: Feature-Dependency-Node

#6817 Simplify PackageDependencyModel construction
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/RuleHandlers/PackageRuleHandler.cs
Labels: Feature-Dependency-Node, auto-merge

#6818 Fix tab stops to follow top to bottom order.
  src/Microsoft.VisualStudio.Editors/PropPages/BuildPropPage.resx
  src/Microsoft.VisualStudio.Editors/PropPages/CodeAnalysisPropPage.resx
Labels: Feature-Legacy-Application-Designer, Tenet-User Friendly

#6824 Suppress validation of active target framework
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshotTests.cs
Labels: Feature-Dependency-Node

#6823 Prevent NullReferenceException in StartupProjectRegistrar
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/StartupProjectRegistrar.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/ProjectSystem/VS/DebugTests/StartupProjectRegistrarTests.cs
Labels: Feature-Debugging

#6712 Remove target framework moniker parsing code
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Properties/InterceptedProjectProperties/TargetFrameworkMonikerValueProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/TargetFrameworkProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/ITargetFrameworkProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Frameworks/TargetFramework.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesTreeViewProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependencyTreeTelemetryService.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Models/TargetDependencyViewModel.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/DependenciesSnapshot.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Snapshot/TargetedDependenciesSnapshot.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/Subscriptions/DependenciesSnapshotProvider.ContextTracker.cs
  tests/Microsoft.VisualStudio.ProjectSystem.IntegrationTests/DependencyNodeIntegrationTests.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/Mocks/IMockDependenciesViewModelFactory.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/Tree/Dependencies/Models/DependenciesViewModelFactoryTests.cs
Labels: Feature-Dependency-Node

#6828 Avoid calling expensive method in common case
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/CrossTarget/AggregateCrossTargetProjectContextProvider.cs
Labels: Feature-Dependency-Node, Performance-Scenario-Solution-Open, Tenet-Performance

#6822 BuildUpToDateCheck subscribes for updates lazily
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.cs
  tests/Microsoft.VisualStudio.ProjectSystem.Managed.UnitTests/ProjectSystem/UpToDate/BuildUpToDateCheckTests.cs
Labels: Feature-Up-to-date, Performance-Scenario-Solution-Open, Tenet-Performance

#6863 Add `main` branch trigger to yml files
  build/ci/richnav.yml
  build/ci/unit-tests.yml
Labels: Area-Infrastructure, auto-merge

#6864 Remove triggers referencing master
  build/ci/richnav.yml
  build/ci/unit-tests.yml
Labels: Area-Infrastructure, auto-merge

#6861 Add telemetry to track when properties pages are already opened.
  src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerView.vb
  src/Microsoft.VisualStudio.AppDesigner/ApplicationDesigner/ApplicationDesignerWindowPane.vb
  src/Microsoft.VisualStudio.AppDesigner/Common/Utils.vb
Labels: Feature-Legacy-Application-Designer

#6872 Fix race condition in LaunchSettingsProvider
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Debug/LaunchSettingsProvider.cs
Labels: Bug, Feature-Debugging

#6882 Fix up-to-date check hang in command line mode
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/UpToDate/BuildUpToDateCheck.Subscription.cs
Labels: Feature-Up-to-date
