Repository dotnet/project-system, pull requests merged in 2024-06, with the labels that each got.

#9468 Rename the legacy "Managed Resource Editor" editor factory
  src/Microsoft.VisualStudio.Editors/VSPackage.resx
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.cs.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.de.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.es.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.fr.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.it.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ja.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ko.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pl.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.pt-BR.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.ru.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.tr.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hans.xlf
  src/Microsoft.VisualStudio.Editors/xlf/VSPackage.zh-Hant.xlf
Labels: Feature-Resource-Designer

#9483 Send telemetry when CodeModel is used
  src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/LanguageServices/ProjectContextCodeModelProvider.cs
  src/Microsoft.VisualStudio.ProjectSystem.Managed/Telemetry/TelemetryEventName.cs
Labels: Feature-Language-Service, Tenet-Performance, Performance-Scenario-Solution-Open

#9486 Add CollectNuGetAuditSupressions target
  src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets
Labels: auto-merge
